In [2]:
#Zad 1
import pandas as pd
import numpy as np

data = pd.read_csv('president_heights.csv')
heights = np.array(data['height(cm)'])
#print(data)
print(heights)

print('Mean height: ',np.mean(heights))
print('Standard deviation: ',np.std(heights))
print('Minimum height: ',heights.min())
print('Maximum height: ',heights.max())
print('25th percentile: ',np.percentile(heights, 25))
print('Median: ',np.median(heights))
#print('Median: ',np.percentile(heights, 50))
print('75th percentile: ',np.percentile(heights, 75))

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]
Mean height:  179.73809523809524
Standard deviation:  6.931843442745892
Minimum height:  163
Maximum height:  193
25th percentile:  174.25
Median:  182.0
75th percentile:  183.0


In [14]:
#Zad 2

data = np.array(pd.read_csv('Zadanie_2.csv',sep=";", header=None))
print(data)

# podpunkt - a
w,v = np.linalg.eig(data)
print("wartości własne",w)
print("wektory własne",v)

# podpunkt - b
inverse = np.linalg.inv(data)
print(inverse)

[[  1   2  15 -59   9   3  75   6   7   1]
 [  0   5   0   4   6  16  44   7   1   1]
 [  7  14   3 -10   9  15  73   8   2   9]
 [  1   5  15 -54   5  15  35   8   6   4]
 [  0   8   5 -18   7  16  91   6   7   9]
 [  7  18  23 -90   4   8  31   0   1   7]
 [  2   8  20 -72   4   1  91   9   4   4]
 [  4  12  18 -65   6   9  76   4   9   9]
 [  7  15  13 -52   5   7  54   2   7   0]
 [  2   9  15 -56   6   1  98   4   8   4]]
wartości własne [104.34960192 +0.j         -23.35660516+18.84992811j
 -23.35660516-18.84992811j  15.92989017 +0.j
  -4.99456452 +0.j           0.35205717 +5.80125175j
   0.35205717 -5.80125175j  -1.03383491 +0.j
   3.87900166 +1.42651533j   3.87900166 -1.42651533j]
wektory własne [[-0.29000475+0.j         -0.07545445+0.07743149j -0.07545445-0.07743149j
  -0.03544485+0.j          0.42681634+0.j         -0.22172831-0.29869259j
  -0.22172831+0.29869259j  0.41343726+0.j         -0.28670255+0.21891569j
  -0.28670255-0.21891569j]
 [-0.24163153+0.j          0.41229621+0

In [3]:
# zadanie 3
rainfall=pd.read_csv('Seattle2014.csv')['PRCP'].values
inches=rainfall/254.0
inches.shape

(365,)

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline 
sns.set()
plt.hist(inches, 40)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1686962592.py, line 1)

In [ ]:
# liczba dni kiedy nie padało
print("Number days without rain: ", np.count_nonzero(inches == 0))

In [ ]:

# liczba dni kiedy padało
print("Number days with rain: ", np.count_nonzero(inches != 0))

In [ ]:
# liczba dni kiedy padało powyżej 0.5
print("Days with more than 0.5 inches:", np.count_nonzero(inches > 0.5))

In [ ]:
# liczba dni kiedy padało ponizej 0.2
print("Rainy days with < 0.2 inches  :", np.count_nonzero((inches > 0) & (inches < 0.2)))

In [ ]:
# Medianę opadów w deszczowe dni w 2014 roku 
rainy = inches[inches > 0].copy()
print("Median precip on rainy days in 2014 (inches): ", np.median(rainy))

In [ ]:
summer_2014 = inches[171:262].copy() # z 262 dniem włącznie
print("Median precip on summer days in 2014 (inches): ", np.median(summer_2014))

In [ ]:
print("Maximum precip on summer days in 2014 (inches): ", np.max(summer_2014))

In [ ]:
inches[171:262] = -1.
without_the_summer = inches[inches != -1].copy()
print("Maximum precip on non-summer rainy days (inches):", np.max(without_the_summer))

In [ ]:
# zadanie 4
A = np.array([0,3,2,5])
B = np.array([0,3,1,4])

In [ ]:
# Dodaj A i B 
np.add(A, B)

In [ ]:
# Odejmij B od A 
np.subtract(A, B)

In [ ]:
# Pomnóż wektor A przez skalar a=4
np.multiply(A, 4)

In [ ]:
# Oblicz iloczyn skalarny wektorów A i B
np.dot(A, B)

In [ ]:
# Znajdź długość wektora B 
B.size